# 개발환경 : base package 로그 레벨
logging.level.com.rookies6.myspringbootlab=DEBUG

# H2 (in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
