spring.application.name=MySpringBootLabProject

# 사용자가 정의한 환경변수
myprop.username=springboot
myprop.port=${random.int(1,100)}

# 현재 활성화된 프로파일 (prod : MariaDB / test : H2)
spring.profiles.active=prod

# 실행되는 SQL 출력
spring.jpa.show-sql=true
