# 운영환경 : base package 로그 레벨
logging.level.com.rookies6.myspringbootlab=INFO

# MariaDB lab 계정
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=update
