# 운영환경 : base package 로그 레벨
logging.level.com.rookies6.myspringbootlab=INFO

# MariaDB lab 계정
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=update
# 지연 로딩 대상을 in 절로 묶어 한 번에 조회 (N+1 쿼리 튜닝)
spring.jpa.properties.hibernate.default_batch_fetch_size=100
